/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadotrueque;

import java.awt.Color;

/**
 *
 * @author gonza
 */
public class JFPublicacion extends javax.swing.JFrame {

    /**
     * Creates new form JFPublicacion
     */
    public JFPublicacion() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(bgGif, "src/img/lluvia2.gif");
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    public void agregarInfo(Aviso aviso){///////a fututo aplicar formato a cada string
        titulo.setText(aviso.getTitulo());
        descripcion.setText(formatoDescripcion(aviso.getDescripcion()));
        //formatoDescripcion(aviso.getDescripcion());
        //descripcion.setText(aviso.getDescripcion());
        alonsoCoin.setText("AlonsoCoin = "+aviso.getAlonsoCoin());
        precio.setText("Precio = "+aviso.getPrecio());
        nickname.setText("Nickname [ "+aviso.getCuentaPublicador().getNickname()+" ]");
        region.setText("Region [ "+aviso.getRegion()+" ]");
    }
    private String formatoDescripcion(String texto){
        //String textoNuevo="<html>";
        /*
        int extension=30;
        for(int i=0;i<texto.length()-1;i++){
            textoNuevo+=texto.charAt(i);
            if(i!=0 && i%extension == 0){
                if(texto.charAt(i)==' ' && texto.charAt(i+1)==' ')  textoNuevo+=" -";
                textoNuevo+="<br>";
            }
        }
        */
        //textoNuevo+=texto;
        return "<html>"+texto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pi = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        descripcion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        alonsoCoin = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        nickname = new javax.swing.JLabel();
        region = new javax.swing.JLabel();
        pbotones = new javax.swing.JPanel();
        botonCompra = new javax.swing.JButton();
        botonTrueque = new javax.swing.JButton();
        bgGif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("- Aviso -");
        setName("- Aviso -"); // NOI18N
        setResizable(false);

        pi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setBackground(new java.awt.Color(255, 255, 204));
        info.setOpaque(false);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("titulo");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descripcion.setForeground(new java.awt.Color(255, 255, 255));
        descripcion.setText("asfds");
        descripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        descripcion.setAlignmentX(0.1F);
        descripcion.setAlignmentY(1.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(52, 57, 102));

        alonsoCoin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alonsoCoin.setForeground(new java.awt.Color(255, 255, 255));
        alonsoCoin.setText("AlonsoCoin =");
        alonsoCoin.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(255, 255, 255));
        precio.setText("Precio =");
        precio.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nickname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nickname.setForeground(new java.awt.Color(255, 255, 255));
        nickname.setText("Nickname [ ");
        nickname.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        region.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        region.setForeground(new java.awt.Color(255, 255, 255));
        region.setText("Region [ ");
        region.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nickname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alonsoCoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addComponent(region, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(alonsoCoin)
                .addGap(19, 19, 19)
                .addComponent(precio)
                .addGap(18, 18, 18)
                .addComponent(nickname)
                .addGap(18, 18, 18)
                .addComponent(region)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pi.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 390));

        pbotones.setBackground(new java.awt.Color(255, 204, 204));
        pbotones.setOpaque(false);

        botonCompra.setBackground(new java.awt.Color(102, 170, 192));
        botonCompra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonCompra.setText("Compra");
        botonCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        botonCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCompraMouseExited(evt);
            }
        });

        botonTrueque.setBackground(new java.awt.Color(102, 170, 192));
        botonTrueque.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonTrueque.setText("Trueque");
        botonTrueque.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        botonTrueque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTrueque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonTruequeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonTruequeMouseExited(evt);
            }
        });
        botonTrueque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTruequeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pbotonesLayout = new javax.swing.GroupLayout(pbotones);
        pbotones.setLayout(pbotonesLayout);
        pbotonesLayout.setHorizontalGroup(
            pbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbotonesLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(botonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(pbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pbotonesLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(botonTrueque, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(331, Short.MAX_VALUE)))
        );
        pbotonesLayout.setVerticalGroup(
            pbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbotonesLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(botonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(pbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pbotonesLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(botonTrueque, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        pi.add(pbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 580, 130));

        bgGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lluvia2.gif"))); // NOI18N
        pi.add(bgGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pi, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTruequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTruequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTruequeActionPerformed

    private void botonTruequeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTruequeMouseEntered
        //botonTrueque.setBackground(Color.White);
        botonTrueque.setBackground(new Color(119,206,211));
    }//GEN-LAST:event_botonTruequeMouseEntered

    private void botonTruequeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTruequeMouseExited
        botonTrueque.setBackground(new Color(102,170,192));
    }//GEN-LAST:event_botonTruequeMouseExited

    private void botonCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCompraMouseExited
        botonCompra.setBackground(new Color(102,170,192));
    }//GEN-LAST:event_botonCompraMouseExited

    private void botonCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCompraMouseEntered
        botonCompra.setBackground(new Color(119,206,211));
    }//GEN-LAST:event_botonCompraMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPublicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alonsoCoin;
    private javax.swing.JLabel bgGif;
    private javax.swing.JButton botonCompra;
    private javax.swing.JButton botonTrueque;
    private javax.swing.JLabel descripcion;
    private javax.swing.JPanel info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nickname;
    private javax.swing.JPanel pbotones;
    private javax.swing.JPanel pi;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel region;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
